summary.file.path=latency-summary.xlsx
output.directory=reports/
input.folder.path=logs
metrics.latency.windowSizeSeconds=1

report.file.path=classpath:report-template.xlsx
#used in logback-spring.xml configs for logger
app.log.path=C:/Users/Martin F - PC Desk/Desktop/caja/var/delay-report-generator/logs/

