metrics.latency.windowSizeSeconds=1

report.file.path=classpath:report-template.xlsx
input.folder.path=C:/Users/Martin F - PC Desk/Desktop/caja/var/monitor_delay_md/logs

#used in logback-spring.xml configs for logger
app.log.path=C:/Users/Martin F - PC Desk/Desktop/caja/var/delay-report-generator/logs/

temp.folder.path=C:/Users/Martin F - PC Desk/Desktop/caja/var/delay-report-generator/temp/
summary.file.path=C:/Users/Martin F - PC Desk/Desktop/caja/var/delay-report-generator/temp/latency-summary.xlsx
output.folder.path=C:/Users/Martin F - PC Desk/Desktop/caja/var/delay-report-generator/reports/

